# Generated by Django 4.0.3 on 2022-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GEOJson', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
